#!/bin/bash

PROJECT_NAME="Ellipsoid"

PARAMS=""

EXAMPLE=""

while getopts "r:ETRD" arg
do
    case "$arg" in
        r)
            EXAMPLE="${OPTARG}"
            ;;
        S)
            PARAMS+=" -DELLIPSOID_BUILD_SHARED_LIBS=ON"
            ;;
        E)
            PARAMS+=" -DELLIPSOID_BUILD_EXAMPLES=ON"
            ;;
        T)
            PARAMS+=" -DELLIPSOID_BUILD_TESTS=ON"
            ;;
        R)
            PARAMS+=" -DMAKE_BUILD_TYPE:STRING=Release"
            ;;
        D)
            PARAMS+=" -DMAKE_BUILD_TYPE:STRING=Debug"
            ;;
    esac
done

cmake -S . -B ./build/ -G "MinGW Makefiles" $PARAMS
cmake --build ./build/

if [[ "${EXAMPLE}" != "" ]]
then
    ./build/examples/${EXAMPLE}.exe
fi

