#!/bin/bash

PROJECT_NAME="Ellipsoid"

cmake -S . -B ./build/
cmake --build ./build/

while getopts "re:" arg
do
    case "$arg" in
        r)
            ./build/src/$PROJECT_NAME
            ;;
        e)
            ./build/examples/${OPTARG}/example
            ;;
    esac
done
